name: mock_fleet_api
description: A Dart package implementing FleetApi via Dio to fetch remote fleet data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  fleet_api:
    path: ../fleet_api
  logger: ^2.6.2

dev_dependencies:
  mocktail: ^1.0.4
  test: any
  very_good_analysis: ^10.0.0
