name: hive_fleet_api
description: A Flutter package implementing FleetApi using local storage (Hive) with polling for real-time updates.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  fleet_api:
    path: ../fleet_api
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  meta: ^1.17.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.10.4
  hive_ce_generator: ^1.10.1
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^10.0.0
