name: fleet_api
description: A Dart package providing abstract API interfaces and models for fleet monitoring.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  test: ^1.28.0
  very_good_analysis: ^10.0.0
